version: '3.1'

services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "53603:53603"
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pg.com
      PGADMIN_DEFAULT_PASSWORD: admin#
  web:
    image: caffeines/freshagric:v0.0.1-beta
    container_name: freshagric
    restart: always
    env_file: dev.env
    ports:
        - 4400:4400
    volumes:
        - .:/home/freshagric/app
        - /home/freshagric/app/node_modules
    command: node app.js
    networks:
      - app-network
networks:
  app-network:
    driver: bridge