version: '3.1'

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    image: freshagric
    container_name: freshagric
    restart: always
    env_file: prod.env
    ports:
        - 80:4400
    volumes:
        - .:/home/freshagric/app
        - /home/freshagric/app/node_modules
    command: node app.js
    depends_on:
        - redis
    networks:
      - app-network
  redis:
    image: redis
    container_name: freshagric-redis
    volumes:
      - redis_data:/data
    command: redis-server --requirepass password
    ports:
      - '6379:6379'
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: freshagric-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network
volumes:
  redis_data:
networks:
  app-network:
    driver: bridge