version: '3.1'

services:
  redis:
    image: redis
    container_name: freshagric-redis
    volumes:
      - redis_data:/data
    command: redis-server --requirepass password
    ports:
      - '6379:6379'
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: freshagric-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network
volumes:
  redis_data:
networks:
  app-network:
    driver: bridge